## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [15]:
import numpy as np
print(np.linspace(-1.3, 2.5,65))


[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [14]:
import numpy as np
n=int(input())
print(np.array([i%3+1 for i in range(3*n) ]))

2
[1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [ ]:
import numpy as np
print(np.array([i for i in range(20) if i%2!=0 ]))

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [20]:
array=np.zeros((10, 10))
for i in range(10):
    array[0][i]=1
    array[9][i]=1
    array[i][0]=1
    array[i][9]=1
print(array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [36]:
array=np.zeros((8,8))
for i in range(8):
    for k in range(i%2,8,2):
        array[i][k]=1
print(array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [90]:
import numpy as np
n=int(input())
a=np.eye(n)
for i in range(n):
    for j in range(n):
        a[i][j]=(i+j)
print(a)


5
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


##### 7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [39]:
def np_multiply(A,B):
    return np.dot(A, B)
A = np.random.randint(10, size=(n, n))
B = np.random.randint(1, 10, n)
print(A,'\n\n',B,'\n','results:')
print(np.multiply(B,B),'\n\n',np.multiply(A,B),'\n\n',np.multiply(A,A))

[[4 3 3 2 7 8 6 0 6 1]
 [0 4 5 2 0 5 6 0 0 6]
 [9 4 5 1 7 5 7 1 8 7]
 [3 9 8 3 4 8 8 9 8 7]
 [6 9 6 0 9 7 7 3 2 5]
 [7 6 6 9 4 6 7 5 6 7]
 [2 3 2 5 6 6 1 8 4 4]
 [4 7 9 5 3 8 8 2 4 3]
 [7 2 8 4 2 0 9 4 8 4]
 [1 3 1 7 0 5 6 1 5 4]] 

 [2 7 8 5 7 4 8 5 6 8] 
 results:
[ 4 49 64 25 49 16 64 25 36 64] 

 [[ 8 21 24 10 49 32 48  0 36  8]
 [ 0 28 40 10  0 20 48  0  0 48]
 [18 28 40  5 49 20 56  5 48 56]
 [ 6 63 64 15 28 32 64 45 48 56]
 [12 63 48  0 63 28 56 15 12 40]
 [14 42 48 45 28 24 56 25 36 56]
 [ 4 21 16 25 42 24  8 40 24 32]
 [ 8 49 72 25 21 32 64 10 24 24]
 [14 14 64 20 14  0 72 20 48 32]
 [ 2 21  8 35  0 20 48  5 30 32]] 

 [[16  9  9  4 49 64 36  0 36  1]
 [ 0 16 25  4  0 25 36  0  0 36]
 [81 16 25  1 49 25 49  1 64 49]
 [ 9 81 64  9 16 64 64 81 64 49]
 [36 81 36  0 81 49 49  9  4 25]
 [49 36 36 81 16 36 49 25 36 49]
 [ 4  9  4 25 36 36  1 64 16 16]
 [16 49 81 25  9 64 64  4 16  9]
 [49  4 64 16  4  0 81 16 64 16]
 [ 1  9  1 49  0 25 36  1 25 16]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [23]:
A = np.cos(np.arange(0, 1, 0.05))
B = np.sin(np.arange(0, 1, 0.05))
print('горизонтальное объединение\n',np.vstack((A,B)),'\n')
print('вертикальное объединение\n',np.hstack((A,B)))

горизонтальное объединение
 [[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309]
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155 ]] 

вертикальное объединение
 [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.         0.04997917 0.09983342 0.14943813
 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834 0.43496553
 0.47942554 0.52268723 0.56464247 0.60518641 0.64421769 0.68163876
 0.71735609 0.75128041 0.78332691 0.8134155 ]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [115]:
A=np.random.rand(3, 5)
print(A*4-1)

[[-0.90434526  2.16785498  2.81710767  2.94926541 -0.23892612]
 [ 0.94965699  2.53865756 -0.43122704  0.05868312  2.07932567]
 [ 2.331918    1.91216303  2.90915856  0.23991838  1.40949792]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [116]:
print('сумма всех элементов', A.sum())
print('сумма внутри столбцов', np.sum(A, axis=0))
print('сумма внутри строк', np.sum(A, axis=1))
print('среднее значение',np.mean(A, axis = 1))
print('дисперсия',np.var(A, axis = 1))
print('стандартное отклонение',np.std(A, axis = 1))

сумма всех элементов 8.94717721801484
сумма внутри столбцов [1.34430743 2.40466889 2.0737598  1.56196673 1.56247437]
сумма внутри строк [2.94773917 2.54877408 3.45066397]
среднее значение [0.58954783 0.50975482 0.69013279]
дисперсия [0.16231706 0.08077276 0.05130384]
стандартное отклонение [0.40288591 0.2842055  0.22650352]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [117]:

B = np.mean(A, axis = 1)
C = np.std(A, axis = 1)
print('matrix:\n',A,'\nmean:\n',B,'\nstd\n',C)
for i in range(3):
    for j in range(5):
        A[i][j] = (A[i][j]-B[i])/C[i]
print('result:\n',A)

matrix:
 [[0.02391368 0.79196375 0.95427692 0.98731635 0.19026847]
 [0.48741425 0.88466439 0.14219324 0.26467078 0.76983142]
 [0.8329795  0.72804076 0.97728964 0.3099796  0.60237448]] 
mean:
 [0.58954783 0.50975482 0.69013279] 
std
 [0.40288591 0.2842055  0.22650352]
result:
 [[-1.40395613  0.50241496  0.90529122  0.98729815 -0.99104821]
 [-0.07860709  1.31914962 -1.29329509 -0.86234797  0.91510053]
 [ 0.63065997  0.16736148  1.26778093 -1.67835448 -0.3874479 ]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [118]:
print('отсортированная матрица\n')
print(A[A[:,2].argsort()])

отсортированная матрица

[[-0.07860709  1.31914962 -1.29329509 -0.86234797  0.91510053]
 [-1.40395613  0.50241496  0.90529122  0.98729815 -0.99104821]
 [ 0.63065997  0.16736148  1.26778093 -1.67835448 -0.3874479 ]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [119]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))
print('B:\n',B,'\n\nC:\n',C)
print('Обе эти матрицы симметричны; первая размером 5 на 5, вторая 3 на 3; их сходство в том, что они симметричны; отличие в значениях элементов, размере. Кроме того, у второй матрицы элементы главной диагонали 5-ки, а у первой разные числа. Однако, сумма диагноальных элементов одинакова ')

B:
 [[ 2.37500389 -0.7035149  -0.36978831 -2.37680762  1.07510693]
 [-0.7035149   2.02058638 -1.03904018 -0.92242452  0.64439322]
 [-0.36978831 -1.03904018  4.09943288 -0.11872306 -2.57188133]
 [-2.37680762 -0.92242452 -0.11872306  4.53527543 -1.11732024]
 [ 1.07510693  0.64439322 -2.57188133 -1.11732024  1.96970142]] 

C:
 [[ 5.         -2.15599058 -0.9266798 ]
 [-2.15599058  5.         -0.37564257]
 [-0.9266798  -0.37564257  5.        ]]
Обе эти матрицы симметричны; первая размером 5 на 5, вторая 3 на 3; их сходство в том, что они симметричны; отличие в значениях элементов, размере. Кроме того, у второй матрицы элементы главной диагонали 5-ки, а у первой разные числа. Однако, сумма диагноальных элементов одинакова 


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [120]:
print('сумма диагональных элементов матрицы В:\n',np.trace(B))
print('сумма диагональных элементов матрицы С:\n',np.trace(C))

сумма диагональных элементов матрицы В:
 15.0
сумма диагональных элементов матрицы С:
 15.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [125]:
print('Детерминант матрицы В:', np.linalg.det(B),'\n','Детерминант матрицы С:',np.linalg.det(C),'\n У А посчитать нельзя')
print('Ранг матрицы А', np.linalg.matrix_rank(A),'\n','Ранг матрицы В',np.linalg.matrix_rank(B),'\n Ранг матрицы С',np.linalg.matrix_rank(C))
S1=np.linalg.eig(B)
S2=np.linalg.eig(C)
print('\nСобственные значения матрицы B\n', S1[0], '\nСобственные значения матрицы С\n',S2[0])
print('\n кол-во собственных занчений равно размерности матрицы')




Детерминант матрицы В: 1.0014536853190524e-30 
 Детерминант матрицы С: 95.2583067033638 
 У А посчитать нельзя
Ранг матрицы А 3 
 Ранг матрицы В 3 
 Ранг матрицы С 3

Собственные значения матрицы B
 [7.23051530e+00 5.26920590e+00 2.50027880e+00 8.34650164e-16
 1.42451349e-16] 
Собственные значения матрицы С
 [2.5002788 7.2305153 5.2692059]

 кол-во собственных занчений равно размерности матрицы


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [127]:
np.random.seed(1032201711)
print(np.random.randint(9))

8


In [128]:
print('Аналитическое решение интеграла номер 8: 0,39056208')
print('Аналитическое решение интеграла номер 9: 1,11072073')

Аналитическое решение интеграла номер 8: 0,39056208
Аналитическое решение интеграла номер 9: 1,11072073


In [10]:
import numpy as np
#from scipy.special import logsumexp
def f8(x):
    return (2*x-1)/(2*x+1)

def f9(x):
    #return logsumexp( 1/np.sqrt(2+3*x-2*x**2, where = x!=2))
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def compute_integrate(f,a, b, eps, method):
    n = int((b-a) / eps)
    xx = np.linspace(a, b, n,endpoint=False)
    if method == 'rect':
        I=eps*np.sum(f(xx))
    elif method == 'trap':
        I=eps/2*(f(xx[0]) + 2*np.sum(f(xx[1:-1])) + f(xx[-1]))
    elif method == 'simpson':
        I=eps/3*(f(xx[0]) + 2*np.sum(f(xx[2:-1:2])) + 4*np.sum(f(xx[1:-2:2])) + f(xx[-1]))
    return I
        
    
print('интеграл 4:', compute_integrate(f8, 0, 2, 0.00001, 'rect') )
print('интеграл 4:', compute_integrate(f8, 0, 2, 0.00001, 'trap') )
print('интеграл 4:', compute_integrate(f8, 0, 2, 0.00001, 'simpson'))
print('интеграл 9:', compute_integrate(f9, 3/4, 2, 0.00000001, 'rect'))
print('интеграл 9:', compute_integrate(f9, 3/4, 2, 0.00000001, 'trap') )
print('интеграл 9:',compute_integrate(f9, 3/4, 2, 0.00000001, 'simpson'))
print('Я получила отличие в ответах в 5 знаке после запятой.\n Вывод: с уменьшением шага решения, ответ получается точнее ')






интеграл 4: 0.3905521347234617
интеграл 4: 0.3905541347314617
интеграл 4: 0.3905461348061291
интеграл 9: 1.110655428329193
интеграл 9: 1.1106330648209233
интеграл 9: 1.1106197214376308
Я получила отличие в ответах в 5 знаке после запятой.
 Вывод: с уменьшением шага решения, ответ получается точнее 
